dist: xenial
language: python
python:
- 3.7
cache:
  apt: true
addons:
  apt:
    packages:
    - verilator
before_install:
- pip install -U pip
install:
- pip install pytest-cov
- pip install -r requirements.txt
- pip install -e .
script:
- pytest tests/
